# Generated by Django 4.2.9 on 2024-02-23 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('report_text', models.TextField(default="")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.report')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['submission_date', 'status'], name='shared_repo_submiss_d42c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['report', 'file'], name='shared_file_report__7eff70_idx'),
        ),
    ]
