# Generated by Django 4.2.11 on 2024-03-18 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='report',
            name='shared_repo_submiss_d42c9d_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='incident_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='incident_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='report_summary',
            field=models.TextField(default='summary to be provided'),
        ),
        migrations.AddField(
            model_name='report',
            name='students_involved',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['submission_date', 'status', 'incident_date', 'incident_location'], name='shared_repo_submiss_9681ca_idx'),
        ),
    ]
