# Generated by Django 4.2.11 on 2024-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_remove_report_shared_repo_submiss_d42c9d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='incident_category',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
