# Generated by Django 4.2.11 on 2024-03-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_remove_report_report_text_report_incident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
