# Generated by Django 4.2.11 on 2024-03-18 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('background_info', models.TextField()),
                ('involved_students', models.TextField()),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
